version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/apitest
    steps:
      - checkout
      - run: make test
  crosscompile:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/apitest_cross
    steps:
      - checkout
      - run: go get -u github.com/mitchellh/gox
      - run: GOOS=windows go get -u github.com/spf13/cobra
      - run: make gox
      - run: cd bin/ && git tag -l 'v*' | tail -1 > version
      - persist_to_workspace:
          root: ~/apitest_cross
          paths:
            - bin/
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    working_directory: ~/apitest_cross
    steps:
      - attach_workspace:
          at: ~/apitest_cross
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(less ~/apitest_cross/bin/version) && rm ~/apitest_cross/bin/version &&
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} --replace ${VERSION} ~/apitest_cross/bin/
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
  crossbuild-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - crosscompile:
          requires:
            - test
      - publish-github-release:
          requires:
            - crosscompile