name: Release

on:
  push:
    tags:
      - '*'
      - '**'

env:
  go_version: 1.22
  slack_channel: github-fylr

jobs:
  release:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/programmfabrik/*"
      FYLR_BOT_ACCESS_TOKEN: ${{ secrets.FYLR_BOT_PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.FYLR_BOT_PERSONAL_ACCESS_TOKEN }}

      - name: Set up Go ${{ env.go_version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.FYLR_BOT_PERSONAL_ACCESS_TOKEN }}

      - name: Notify slack channel about a failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.K8S_DEPLOYMENT_SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ${{ env.slack_channel }}
          SLACK_USERNAME: fylr-bot
          SLACK_ICON: https://avatars.githubusercontent.com/u/1220228?s=200&v=4
          SLACK_COLOR: "#ff0000"
          SLACK_MESSAGE: Failed to build release
          SLACK_TITLE: Failed to build release
          SLACK_FOOTER: ""