name: Release

on:
  push:
    tags:
      - '*'
      - '**'

env:
  go_version: 1.18

jobs:
  release:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/programmfabrik/*"
      FYLR_BOT_ACCESS_TOKEN: ${{ secrets.FYLR_BOT_PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.FYLR_BOT_PERSONAL_ACCESS_TOKEN }}          

      - name: Set up Go ${{ env.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go_version }}

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.FYLR_BOT_PERSONAL_ACCESS_TOKEN }}