name: Release

on:
  push:
    tags:
      - '*'
      - '**'

jobs:
  release:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/programmfabrik/*"
      FYLR_BOT_ACCESS_TOKEN: ${{ secrets.FYLR_BOT_PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: replace https://github.com
        shell: bash
        run: git config --global url."https://fylr-bot:$FYLR_BOT_ACCESS_TOKEN@github.com/".insteadOf "https://github.com/"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.FYLR_BOT_PERSONAL_ACCESS_TOKEN }}