name: unit-tests

on:
  push:
    branches:
      - "**"
      - "!production"

env:
  go_version: 1.22
  slack_channel: github-fylr

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Run go ${{ env.go_version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: execute unit tests
        shell: bash
        run: make test

      - name: execute apitest
        shell: bash
        run: make apitest

      - name: Notify slack channel about a failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.K8S_DEPLOYMENT_SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ${{ env.slack_channel }}
          SLACK_USERNAME: fylr-bot
          SLACK_ICON: https://avatars.githubusercontent.com/u/1220228?s=200&v=4
          SLACK_COLOR: "#ff0000"
          SLACK_MESSAGE: Unit tests failed
          SLACK_TITLE: Unit tests failed
          SLACK_FOOTER: ""
